debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: benchmark
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: world
    sql-migration-prefix: v
    locations:
      - classpath:db/migrations
    url: jdbc:mysql://localhost:3306?allowPublicKeyRetrieval=true&useSSL=false
    user: root
    password: benchmark
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level: DEBUG
